services:
  lab1:
    build:
      context: ./HighPy1
      dockerfile: Dockerfile1
    volumes:
      - ./HighPy1/results:/app/results
  
  lab2:
    build:
      context: ./HighPy2
      dockerfile: Dockerfile2
    volumes:
      - ./HighPy2/results:/app/results
